### ISSUE TITLE
Whitespace

### ISSUE THREAD

**Issue by Nate-Wilkins** [tallesl/net-Interpolate#1]
I'm trying to format strings that look something like this:
```C#
var formatted = "Hello { World }".HanselmanFormat(new { World = "World!" });
```
The whitespace is preventing the format from taking place. Is this desirable? Or can this be fixed?

**Comment by tallesl** [comment]
`HaackFormat` and `HenriFormat` seems to work fine with your example.

`HanselmanFormat` and `OskarFormat` just leaves the placeholder and `JamesFormat` throws an exception.

I suggest you to just change the implementation that you are using.
